version: '3.8'

services:
  # Existing PostgreSQL service
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Existing LocalStack service
  localstack:
    image: localstack/localstack:latest
    container_name: s3-localstack
    ports:
      - "4566:4566"  # LocalStack edge port
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - HOSTNAME_EXTERNAL=localhost
      - DEFAULT_BUCKET_NAME=my-bucket
      - PERSISTENCE=0
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Your Spring Boot application
  fpis-app:
    build:
      context: .  # Uses the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: fpis-app
    restart: always
    ports:
      - "8080:8080"  # Expose your app on port 8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_KEY=test
      - AWS_S3_BUCKET=my-bucket
      - AWS_S3_REGION=us-east-1
      - AWS_S3_ENDPOINT=http://localstack:4566
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  localstack_data: